### ISSUE TITLE
can not acces it via mobile

### ISSUE THREAD

**Issue by shinzoke** [joni1802/ts3-manager#16]
hi there i'm been trying acces it via my iphone but for some sort of reason i keep getting a blank screen saying 

... loading

nothing else

**Comment by joni1802** [comment]
Hi,

could be some cache issue. Do it work in a private/incognito tab? 
Clearing all local webpage data and cookies should fix it.

**Comment by shinzoke** [comment]
Nope doesn’t work in incognito... also cleared cookies and browser history

Verstuurd vanaf mijn iPhone

Op 29 aug. 2020 om 20:09 heeft Jonathan <notifications@github.com> het volgende geschreven:

﻿

Hi,

could be some cache issue. Do it work in a private/incognito tab?
Clearing all local webpage data and cookies should fix it.

**Comment by joni1802** [comment]
Which version do you use of the TS3 Manager? Is there any error in the server logs? Which mobile browser do you use?

**Comment by shinzoke** [comment]
i used safari and chrome but gave the same output on the screen => ... loading

at the moment i'm using the latest one that i've found here on github 👍 on my pc it works with a charm 👍 🥇

**Comment by shinzoke** [comment]
error.log show an enormous amount of: 

2020-08-29 20:31:50 | ::ffff:94.110.97.96 | ERROR | Error: could not fetch client with id 1865 in event "cliententerview"
    at events_1.EventEmitter.evcliententerview.clientList.then.clients (/snapshot/ts3-manager/backend/node_modules/ts3-nodejs-library/lib/TeamSpeak.js:167:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)

**Comment by joni1802** [comment]
The logged error is thrown by the [TS3-NodeJS-Library](https://github.com/Multivit4min/TS3-NodeJS-Library). This library is used in the backend and not written by myself. So I cannot help you with that. But I do not think that this error has something to do with the browser issue on mobile.

I guess you are using an iPhone. The TS3 Manager is a PWA (Progressive Web App) and I know that iOS has not the best support for PWAs. Sadly I cannot test the TS3 Manager on iOS right now because I have no iOS device anymore. Though I have tested older versions of it in the past on iOS and it worked.  Maybe you can test it on an android device? So we can isolate the problem.

**Comment by shinzoke** [comment]
damn to bad :s 

and sorry cant test with android since everyone here uses iphone's on ipad's :(

**Comment by joni1802** [comment]
Tested it today on an iPhone myself and it did also not work. I will try to fix this problem.

**Comment by joni1802** [comment]
Version 1.7.2 is now available on sourceforge and docker. This fixed the issue.
