### ISSUE TITLE
Hey mate,

### ISSUE THREAD

**Issue by WolverinDEV** [joni1802/ts3-manager#18]
sadly your website does not contain an imprint, that's why I'm reaching out to you via GitHub.
You may already recognise me, but in case you don't, I'm Markus Hadenfelkt from the TeaSpeak project.

I just received a recommendation for your panel, and tbh, it's one of the rare, structured, modern, responsive and thought threw TS3 - Instance managers. 

As you've guessed, I'm not reaching out for you, just to praise your work, I'm actually thinking of a collaboration.

If you're having any interest feel free to contact me by E-Mail (support@teaspeak.de) or
just join my TeaSpeak server: [ts.teaspeak.de](https://web.teaspeak.de/?connect_default=1&connect_address=87.106.252.164) (<- Click to open the web client).

Best regards

**Comment by joni1802** [comment]
Hello Markus,

thank you for your positive feedback. I have already heard about the TeaSpeak project.
Because the main communication with the ServerQuery is handled by the [TS3-NodeJS-Library](https://github.com/Multivit4min/TS3-NodeJS-Library), which is not officially supporting TeaSpeak servers and not written by myself, I am unable to support TeaSpeak servers either (See [TeaSpeak support #6](https://github.com/joni1802/ts3-manager/issues/6)). The TS3 Manager is more or less just a frontend.

The webpage [https://www.ts3.app](https://www.ts3.app) has no imprint because it is a non-commercial private webpage. I do not make any money with it and have no business running behind this project. Also it is not based in Germany (Server is running in North America). But I have to say that I am not an expert on that topic. Maybe I should do some more research. 

Thanks for the advice.
