### ISSUE TITLE
[Question] Able to One-Click Update TS Server?

### ISSUE THREAD

**Issue by MartinH0** [joni1802/ts3-manager#2]
I just wanted to ask if it is possible with this Manager to also manage (Backup/Import/Export/Update) the managed TS3 Servers or not?

Also I wanted to ask if this WebInterface is able to run on a normal Plesk installation, if so are there any hinte about how to do this?

Best regards,
Martin

**Comment by joni1802** [comment]
> I just wanted to ask if it is possible with this Manager to also manage (Backup/Import/Export/Update) the managed TS3 Servers or not?

Right now it is not possible to create snapshots (backup) or import snapshots (restore) with the TS3 Manager. But these are features I will implement in the future.
Updates cannot be done with the ServerQuery. Because of that, this feature will not be available in the TS3 Manager. 

> Also I wanted to ask if this WebInterface is able to run on a normal Plesk installation, if so are there any hinte about how to do this?

Honestly I have no knowledge about Plesk. The TS3 Manager is written in NodeJS. If Plesk supports NodeJS applications, you can run it in Plesk. But you have to compile it yourself. In the READMEs are the necessary informations for that.

**Comment by joni1802** [comment]
**The  new version (v1.1.1-beta)** is out now and has the feature "Backup/Restore", where you can create and deploy snapshots of your TeamSpeak server. 
It can be downloaded on SourceForge. 
[https://sourceforge.net/projects/ts3-manager/files/](url)

Hope you like it :-)
