### ISSUE TITLE
Feature Request (if I was not blind and overlooked that it already exists)

### ISSUE THREAD

**Issue by TheColin21** [joni1802/ts3-manager#31]
Would be possible to implement a public but self hosted TS viewer (perhabs via PHP, JS or an iframe) via ts3 manager? I really like the app but thats a feature that I couldn't find but that would be very useful for me.

**Comment by joni1802** [comment]
Hello,

no and there will be no feature like this in the future - probably. Mainly because of security concerns and with how the TS3-Manager is programmed.
Take a look at [ts3index.com](ts3index.com). They provide something like this. But bare in mind that it communicates with you TeamSpeak server over the unsecure Telnet protocol (default port 10011) and you need to set some permissions for the ServerQuery Guest user.
