### ISSUE TITLE
Ability to run on a subdirectory

### ISSUE THREAD

**Issue by EinDev** [joni1802/ts3-manager#38]
Currently it seems that all the links are absolute, which prevents it running on a subdirectory.
I would like to use it on a reverse proxy on a subdirectory, which currently doesn't work.

I can fix this myself, so i would be glad to make this my first commit :)

**Comment by joni1802** [comment]
The TS3 Manager is not using any absolute paths. Only relative paths are served by the app (see screenshot). If you want to access the TS3 Manager behind a reverse proxy over a subpath adding a rewrite condition should do the job. 
![Bild_2021-04-11_203345](https://user-images.githubusercontent.com/40319156/114316754-30c09000-9b05-11eb-8212-22f7efe04105.png)

**Comment by EinDev** [comment]
I am sorry, absolute paths is the wrong word. I was talking about using "css/" instead of "/css", so it will work without the rewrite condition.
Unfortunately IIS on Windows Server doesn't have such a rewrite condition (AFAIK), so i cannot get it to work this way on Windows.

**Comment by joni1802** [comment]
This "css/" instead of "/css" is not possibly due to the overall build process of the app. 
Take a look at the following article which describes rewrite conditions in IIS:
[https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/reverse-proxy-with-url-rewrite-v2-and-application-request-routing](https://docs.microsoft.com/en-us/iis/extensions/url-rewrite-module/reverse-proxy-with-url-rewrite-v2-and-application-request-routing)
