### ISSUE TITLE
Ability to make panel accessible through sub directory

### ISSUE THREAD

**Issue by lusu007** [joni1802/ts3-manager#44]
At the moment it is not possible to host ts3-manager in a sub directory e.g. `admin.example.com/teamspeak`.
A simple solution is to add a environment variable for setting the base URL of ts3manager.

**Comment by joni1802** [comment]
The question got already asked (see #38).
It should be no problem to solve this with a rewrite rule in your reverse proxy. 
I will try to post an example config with a rewrite rule for nginx and apache in the next days.

Setting this option with an evironment variable is not possible, because the path is set in the build process of the frontend. The frontend is build with the Vue CLI, which uses Webpack under the hood. 
So if you really want to change the base path, you have to set it before the build process and build the frontend on your own. 
[https://cli.vuejs.org/config/#publicpath](https://cli.vuejs.org/config/#publicpath)

A short overview for how to setup the development environment can be found here: 
 [https://www.ts3.app/guide/Developers.html](https://www.ts3.app/guide/Developers.html)

**Comment by lusu007** [comment]
Oh sorry, I have not seen #38 ...

> I will try to post an example config with a rewrite rule for nginx and apache in the next days.
That's a good idea, since apparently several have already had the problem.
