### ISSUE TITLE
TeaSpeak support

### ISSUE THREAD

**Issue by dudztroyer** [joni1802/ts3-manager#6]
Hey, I'd like to know if this has support for TeaSpeak servers.

Take a look at their official website: https://teaspeak.de/

**Comment by joni1802** [comment]
The TS3 Manager is using the [Multivit4min/TS3-NodeJS-Library](https://github.com/Multivit4min/TS3-NodeJS-Library) in the backend.

Officially this library does not support TeaSpeak Server. See:
Multivit4min/TS3-NodeJS-Library#47

But maybe it could work because TeaSpeak is using the same Server Query syntax like TeamSpeak. You just have to try it.
