### ISSUE TITLE
Request for improvement

### ISSUE THREAD

**Issue by TS3Joke** [joni1802/ts3-manager#67]
Hi, 

Ability to connect via MyTeamSpeak nicknames
The French language
In the future possibility of installing it on a website

Cordially

**Comment by joni1802** [comment]
Hello,

the TS3-Manager uses the ServerQuery from your TeamSpeak. So it needs the login credentials of the ServerQuery to work. Using your MyTeamSpeak nickname for this is not implemented by the TeamSpeak server. This is the reason why it is not possible to implement such a feature. 

Adding support for different languages is a lot of work and needs a lot of refactoring. Currently I am focusing on other features. Maybe in the future. 

I do not quite understand what you mean with "installing on a website". It is already a webserver. So you can just run it on your server. If you want to run it on an Apache or NGINX webserver it is not possible because the backend is writting in NodeJS.  Though there is a CGI Module for running Node on an Apache webserver but I do not see the point here. 

Jonathan
